@hostname = http://localhost:5000

### Keep alive
POST {{hostname}}/api/keep_alive
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "id": "0"
}

### Reset DB
POST {{hostname}}/api/reset_db
Content-Type: application/json
Authorization: {{TOKEN}}

### Get specific table in full
POST {{hostname}}/api/get_table
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "table": "events"
}

### Overview
GET {{hostname}}/api/overview
Accept: application/json


### Stations
GET {{hostname}}/api/stations
Accept: application/json


### Create station
POST {{hostname}}/api/create_station
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "id": "0",
  "name": "Delta",
  "lat": 58.386,
  "lon": 26.726
}


### Create space
POST {{hostname}}/api/create_space
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "station": "0",
  "space": "A"
}


### Delete space
POST {{hostname}}/api/delete_space
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "station": "0",
  "space": "A"
}


### Lock space
POST {{hostname}}/api/lock
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "station": "0",
  "space": "A",
  "rfid": "RFID-12345"
}


### Unlock space
POST {{hostname}}/api/unlock
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "station": "0",
  "space": "A",
  "rfid": "RFID-12345"
}